# fly.toml app configuration file generated for helium-api on 2025-04-13T16:07:43-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'helium-api'
primary_region = 'dfw'

[build]

[env]
  DATABASE_PATH = '/data/db.sqlite'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source = 'helium_primary'
  destination = '/data'
