// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BasicItem = { name: string, barcode: string, current_sell_price: number, current_inventory: number, };
