[package]
name = "helium-types"
version = "0.1.0"
edition = "2024"
rust-version = "1.86.0"

[dependencies]
ts-rs = "10.1.0"
serde = { version = "1.0.219", features = ["derive"] }
tauri-plugin-http = "2.4.3"
