[package]
name = "api-server"
version = "0.1.0"
edition = "2024"
rust-version = "1.86.0"

[dependencies]
sea-orm = { version = "1.1", features = [ "sqlx-sqlite", "runtime-tokio-native-tls", "macros" ] }
tokio = { version = "1.44", features = ["full"] }
axum = "0.8"
helium-types = { path = "../helium-types" }
