[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
rustflags = [
    # Nightly
    "-Zshare-generics=n", # This needs to be off if you use dynamic linking on Windows.
    "-Zthreads=0",
]

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

# [profile.dev.package."*"]
# codegen-backend = "llvm"

# [build]
# incremental = false
